### ISSUE TITLE
关于flutter上的js工具

### ISSUE THREAD

**Issue by mabDc** [huage2580/reader_parser#1]
推荐

首选 https://github.com/ekibun/flutter_qjs 
- 支持windows linux macos android ios 
- 支持async写法 
- 支持设置函数和对象变量到js上下文
- js和dart互操作 省去很多过程
- 应该能满足阅读

其次 https://github.com/abner/flutter_js 
- 实用，但是api不稳定，新旧版本差距大

不推荐

https://github.com/xuelongqy/flutter_jscore 
- 作者没维护

**Comment by huage2580** [comment]
感谢，我也正在为js方面支持调研。
不知道你熟不熟悉上面的，我看qjs只支持了一个channel方法。想要达到对象的完整映射。在js端操作的某个对象，实际是操作dart段的对象。因为阅读的js脚本中，会有使用jsoup的，计划是dart端实现一套jsoup，再完整映射到js

**Comment by mabDc** [comment]
需要我帮忙么，只不过我不太懂怎么帮忙。不妨看看我写的一个
https://github.com/mabDc/eso
[ESO-1.20.18-12018](https://github.com/mabDc/eso/releases/tag/ESO-1.20.18-12018)
[规则wiki](https://github.com/mabDc/eso_source/wiki)
规则导入暂时可用 https://cdn.jsdelivr.net/gh/mabDc/eso_source/manifest

规则解析我有很多花样，可能你不一定喜欢，看你怎么看了

**Comment by huage2580** [comment]
感谢，经过这几天的实践，我最后选择了使用qjs的版本，master和merge_qjs对比实现了两套，后面发现性能差距甚至可以拉开3倍
